### ISSUE TITLE
bread(conf); - missing conf.root?

### ISSUE THREAD

**Issue by gemmadlou** [pvorb/node-bread#12]
When using the suggested config file, I get the following message:

TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at bread (c:\workspace\test\breadproj\node_modules\bread\bread.js:22:21)
    at Object.<anonymous> (c:\workspace\test\breadproj\indx.js:57:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3'

It points to this in bread.js:

for (var key in dir) {
    dir[key] = path.resolve(conf.root, dir[key]);
  }

Am I missing anything, or there a bug?

**Comment by pvorb** [comment]
You are right. I'm sorry. You also need a property `'root'` in the configuration file, which usually has the value of the parent directory of the path returned by [confdir](https://npmjs.org/package/confdir).

I didn't recognize it, since I usually use bread with the executable script provided in `bin/`.

You can either set the root directory to an absolute path manually in the script or you can use the executable script.
Therefore you have to create a configuration file in a directory in the top level directory of your site, e.g. `/var/www/.conf/bread.json`, where `/var/www` is the root.

For an example, see [vorba.ch](/pvorb/vorba.ch/).

I hope this helps.

**Comment by pvorb** [comment]
I'll fix the README when I find the time.

**Comment by gemmadlou** [comment]
Thanks pvorb - will try that

**Comment by pvorb** [comment]
Probably it's the easiest way, if you copy over the "vorba.ch"-repository, delete the blog posts and modify it according to your needs. I don't think there are other users of bread than me, that's why it's lacking documentation.

If you have issues, feel free to ask here again or by email: paul@vorba.ch.
